#Laboratory No.2 : Installment 2: Talking to the User, Author: Mark John A. Rabago

print("=" * 40)
print("            EXPENSE TRACKER")
print("       Know where your money goes.")
print("=" * 40)     
print("")
print("MAIN MENU")
print("  [1] Add an expense            (coming soon)")
print("  [2] View all expenses         (coming soon)")
print("  [3] Show total spent          (coming soon)")
print("  [4] Exit                      (coming soon)")
print("")
name = input("What's your name? ")
print(f"Welcome, {name}! Let's log two expenses.")
firstExpense = input("First expense: ")
amount1 = float(input("Amount of first expense: "))
secondExpense = input("Second expense: ")
amount2 = float(input("Amount of second expense: "))
print("")
print("-" * 40)
print("SUMMARY")
print(f"  - {firstExpense}:\t${amount1:.2f}")
print(f"  - {secondExpense}:\t${amount2:.2f}")
print(f"Total spent:\t${amount1 + amount2:.2f}")
print(f"Average:\t${(amount1 + amount2) / 2:.2f}")
print("Made by: Mark John A. Rabago | Installment 2")