#Laboratory No.3 : Installment 3: The Tracker Does Math, Author: Mark John A. Rabago
print("=" * 40)
print("            EXPENSE TRACKER")
print("       Know where your money goes.")
print("=" * 40)     
print("")
print("MAIN MENU")
print("  [1] Add an expense            (coming soon)")
print("  [2] View all expenses         (coming soon)")
print("  [3] Show total spent          (coming soon)")
print("  [4] Exit                      (coming soon)")
print("")
name = input("What's your name? ")
print(f"Welcome, {name}! Let's log two expenses.")
firstExpense = input("First expense: ")
amount1 = float(input("Amount of first expense: "))
secondExpense = input("Second expense: ")
amount2 = float(input("Amount of second expense: "))
Taxrate = float(input("Tax rate %? "))
budget = float(input("Budget: "))
print("")
print("-" * 40)
print("SUMMARY")
print(f"  - {firstExpense}:\t${amount1:.2f}")
print(f"  - {secondExpense}:\t${amount2:.2f}")
Subtotal = 0 + amount1 + amount2
print(f"Subtotal:\t${Subtotal:.2f}")
print(f"Average:\t${Subtotal / 2:.2f}")
print(f"Tax({Taxrate}%):\t${Subtotal * (Taxrate / 100):.2f}")
grandTotal = Subtotal + (Subtotal * (Taxrate / 100))
print(f"Grand Total:\t${grandTotal:.2f}")
overbudget = grandTotal > budget
print(f"Over budget?\t{overbudget}")
print(f"Left in budget: ${budget - grandTotal:.2f}")
print("-" * 40)
print("Made by: Mark John A. Rabago | Installment 3")